repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ["--verbose", "--safe"]
        # It is recommended to specify the latest version of Python
        # supported by your project here, or alternatively use
        # pre-commit's default_language_version, see
        # https://pre-commit.com/#top_level-default_language_version
        language_version: python3.10
        additional_dependencies: ['click==8.1.3']
  # condlict with pre-commit. Will stay deactivated for now.
  # Run isort manually like this :
  #
  # isort --profile black .
  #
  # while in the project's root directory.
  # - repo: https://github.com/pycqa/isort
  #   rev: 5.6.4
  #   hooks:
  #     - id: isort
  #       args: ["--profile", "black", "--filter-files"]
